### ISSUE TITLE
No drop shadow on Android 8.1

### ISSUE THREAD

**Issue by ghost** [bradmartin/nativescript-cardview#77]
Hi I have an issue with this plugin. I could not get the drop shadow effect to work on Android 8.1. It does not appear neither in ngFor nor in ListView. Radius works fine. I am using Nativescript 3.4.0.

```html
<ListView [items]="studies">
  <ng-template let-study="item">
      <CardView class="cardStyle" elevation="10" margin="10" radius="10">
        <StackLayout class="cardContent">
          <Label [nsRouterLink]="['/study-lists', study.$key]" [text]="study.title"></Label>
        </StackLayout>      
      </CardView>
  </ng-template>
</ListView>
```

```css
.cardStyle {
   backgroud-color: #aaaaaa;
}
.cardContent {
   // ...
}
```
